### ISSUE TITLE
Generate avatar based on hash (feature-request)

### ISSUE THREAD

**Issue by srs** [o1egl/govatar#2]
It would be nice to generate avatars based on hash (like gravatar). For example:

```
govatar generate -hash jenny@foo.bar female
```

The above could then generate an avatar based on the hash provided (like an email) so it would be the same avatar every time.

Would be happy to provide a pull-request for this feature.

BTW, great library and amazing artwork!

**Comment by srs** [comment]
I have implemented this hash technique in a HTTP micro-service build using Govatar. You can see it here https://github.com/srs/govatar-net.

Thanks.

**Comment by o1egl** [comment]
Thank you for great idea.

**Comment by o1egl** [comment]
done in https://github.com/o1egl/govatar/commit/24a017dc0e9680762aeddd75c4f9cd91c55ad5b8
